baseURL = "https://senik.netlify.app/"
languageCode = "en-us"
title = "Senik"
theme = "codex"
ignoreErrors = ["error-remote-getjson"]
copyright = "©MXZ{year}"

[params]
  twitter = "mx_zou"
  github = "millzzzz"
  linkedin = "mengxuanzou"
  showPageTitleInTOC = true

[markup]
  [markup.highlight]
    codeFences = false
    
  # Set to false to disallow raw HTML in markdown files
  [markup.goldmark.renderer]
      unsafe = true

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"