baseURL = "https://mxz.netlify.app/"
languageCode = "en-us"
title = "Senik"
theme = "codex"


[params]
  twitter = "mill_zou"
  github = "senik456"
  linkedin = "mengxuanzou"

[[menu.main]]
  identifier = "about"
  name = "about"
  title = "About"
  url = "/"

[[menu.main]]
  identifier = "blog"
  name = "blog"
  title = "Blog"
  url = "/blog"



